# ==============================================================================
# 14_prioritization.R
# Analysis 14: Prioritisation of substances by regulatory weight and hazard profile
#
# PURPOSE
# -------
# Across European regulatory frameworks (REACH, CLP, Pesticides, OSPAR, etc.),
# thousands of chemical substances are listed, classified, and assessed.  Not
# all listings carry the same regulatory consequence: a substance that merely
# appears in the REACH registration database is treated very differently from
# one placed on the SVHC Candidate List or subject to an authorisation
# obligation.  Likewise, the biological role annotations derived from the ChEBI
# ontology (via `bash/chebi.sh`) provide an independent, semantically grounded
# signal of intrinsic hazard to human health and the environment.
#
# This script combines both dimensions into a composite priority score and
# produces a suite of visualisations that allow policymakers and data stewards
# to identify which substances deserve the most urgent attention, and to
# understand the structural relationships between hazard profiles and regulatory
# classification.
#
# DATA PROVENANCE
# ---------------
# `data/processed/chebi.csv` is generated by `bash/chebi.sh`:
#   1. The ChEBI OWL ontology is downloaded from EBI and converted to Turtle.
#   2. It is merged with the project's substance taxonomy
#      (`data/processed/rdf/substances_taxonomy.ttl`).
#   3. `exact_match_chebi.rq` links project substances to ChEBI entities via
#      InChIKey (skos:exactMatch).
#   4. `chebi_annotaties.rq` extracts biological roles (ChEBI property
#      RO:0000087 "has role") and stores them as OA Annotations.
#   5. `chebi_to_table.rq` exports a flat CSV via GROUP_CONCAT, yielding one
#      row per (substance, name) combination with pipe-separated lists of
#      biological activity labels and ECHA list memberships.
#
# Consequence: only substances with a known InChIKey receive biological
# activity labels (~21.5 % of rows).  Substances without a ChEBI match are
# scored on regulatory list membership alone, which is correct behaviour.
#
# METHODOLOGY
# -----------
# ## Established frameworks used as anchors
#
# | Framework | Role in methodology |
# |---|---|
# | **ToxPi** (Reif et al. 2010, *Environ Health Perspect* 118(12):1714–1720. DOI: 10.1289/ehp.1002180) | Conceptual basis for multi-domain weighted integration: heterogeneous evidence streams (regulatory listing + biological hazard) are combined into a single score through transparent, domain-specific weights. |
# | **REACH Regulation (EC) No 1907/2006, Arts. 57–73** | Legal hierarchy for list weights (0–5): SVHC identification (Art. 57–59) → authorisation/restriction (Art. 60–73).  The weight ranking is derived directly from the legal consequences each instrument triggers. |
# | **CLP Regulation (EC) No 1272/2008, Annex VI** | Basis for harmonised classification weights (weight 2) and CMR hazard weights (weight 3): carcinogenic, mutagenic, and reprotoxic properties are Tier-1 SVHC criteria under Art. 57(a)–(c). |
# | **EU POPs Regulation (EU) 2019/1021** | Basis for POPs list weight (4) and POP bio-hazard weight (3): elimination obligation for persistent organic pollutants is the strongest regulatory signal in the dataset. |
# | **EU Chemicals Strategy for Sustainability, COM(2020) 667 final** | Basis for including neurotoxicity and endocrine disruption as priority hazard classes (bio-hazard weight 2) even though they are not explicit SVHC criteria under Art. 57. |
# | **Regulation (EC) No 1107/2009** | Basis for pesticide approval list weight (2): positive safety determination required before approval. |
#
# ## Own methodological additions
#
# | Choice | Justification |
# |---|---|
# | Numerical scale 0–5 (lists) and 1–3 (bio-hazard) | Not prescribed by any framework; reflects the ordinal REACH hierarchy while remaining interpretable.  ToxPi uses normalised [0,1] domain scores; this project uses raw integers to preserve additivity without normalisation. |
# | Additive summation instead of ToxPi weighted average | The two domains are complementary and largely independent; additive summation avoids normalisation suppressing one domain when the other is zero.  The consequence is an unbounded score interpreted in relative, not absolute, terms. |
# | Neurotoxin and ecotoxin = weight 2 | EU CSS COM(2020) 667 identifies neurotoxicity as a priority hazard class; ecotoxicity is a PBT-adjacent concern (REACH Annex XIII).  Neither is an explicit Art. 57 criterion, so weight 2 (below CMR/POP weight 3) is justified. |
# | Allergen Cat 1A = weight 2; sensitiser Cat 1B = weight 1 | Harmonised CLH endpoint with serious health consequences; weight distinction between confirmed (1A) and probable (1B) sensitisation follows the CLP hazard category structure. |
# | `eu_positive_list` = weight 1 | Administrative oversight signal, not a hazard determination; weight 1 acknowledges regulatory scrutiny without implying concern. |
#
# ## Detailed scoring rationale
# (See the full narrative below for per-instrument legal citations.)
#
# The composite priority score combines two independent evidence domains:
# (1) regulatory list membership and (2) intrinsic biological hazard.
# The multi-domain structure is inspired by the ToxPi (Toxicological Priority
# Index) framework of Reif et al. (2010), which integrates heterogeneous
# evidence streams into a single prioritisation score through transparent,
# domain-specific weights:
#
#   Reif DM, Martin MT, Tan SW, Houck KA, Judson RS, Richard AM, Knudsen TB,
#   Dix DJ, Kavlock RJ. "Endocrine Profiling and Prioritization of
#   Environmental Chemicals Using ToxCast Data." Environ Health Perspect.
#   2010;118(12):1714-1720. DOI: 10.1289/ehp.1002180
#
# DOMAIN 1 — Regulatory list weights (0-5)
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# The weight hierarchy is derived directly from the legal instruments
# established in REACH Regulation (EC) No 1907/2006 and related EU law.
# Each instrument represents a progressively stronger regulatory consequence:
#
#   5 — SVHC Candidate List / SVHC identification
#         Formal identification as a Substance of Very High Concern under
#         REACH Art. 57-59.  Triggers communication obligations (Art. 33)
#         and is a prerequisite for authorisation listing.
#         Source: REACH Reg. (EC) No 1907/2006, Art. 57-59.
#
#   4 — Restriction list / Authorisation list / POPs list
#         Restrictions (Art. 67-73) impose binding conditions or prohibitions.
#         Authorisation (Art. 60-66) requires prior approval for each use.
#         POPs listings impose the strictest environmental controls, including
#         elimination of production and use.
#         Sources: REACH Art. 60-73; EU POPs Regulation (EU) 2019/1021.
#
#   3 — Restriction process / Authorisation process / POPs process /
#       PBT assessment / ED assessment
#         Active regulatory scrutiny under an ongoing process; a final listing
#         determination has not yet been reached.  PBT and ED assessments
#         correspond directly to SVHC criteria under Art. 57(d)-(f).
#         Sources: REACH Art. 57(d)-(f), Annex XIII; REACH Art. 60-73.
#
#   2 — Harmonised CLP classification / CLH process / Pesticide approval
#         Harmonised classifications (CLP Reg. (EC) No 1272/2008, Annex VI)
#         establish legally binding hazard categories, particularly CMR.
#         Pesticide approvals under Reg. (EC) No 1107/2009 confirm biological
#         activity and require a positive safety determination.
#         Sources: CLP Reg. (EC) No 1272/2008, Annex VI;
#                  Reg. (EC) No 1107/2009.
#
#   1 — Dossier evaluation / Substance evaluation / EU positive list
#         Regulatory scrutiny without a final hazard determination.  Positive
#         lists indicate an approved use under active oversight rather than a
#         hazard signal per se.
#
#   0 — REACH registration / sommatie_stoffen / anhydrous
#         Baseline administrative requirements with no inherent hazard
#         determination.  Included to ensure completeness of list membership.
#         Source: REACH Reg. (EC) No 1907/2006, Title II.
#
# OWN METHODOLOGICAL ADDITION — numerical scale:
#   The specific integers (0-5) are not prescribed by any regulatory text or
#   by ToxPi.  They were chosen to reflect the ordinal regulatory hierarchy
#   while keeping the scale interpretable.  The ratio 5:0 (SVHC : registration)
#   mirrors the qualitative difference in legal consequence.
#
# DOMAIN 2 — Biological hazard score (1-3)
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Bio-activity labels are derived from ChEBI biological roles via the
# ontology pipeline (bash/chebi.sh) and reflect intrinsic hazard properties
# independent of any regulatory determination.  The weight tier is aligned
# with the SVHC hazard criteria of REACH Art. 57:
#
#   3 — CMR Cat 1A/1B: carcinogenic, mutagenic, reproductively toxic
#         These are Tier-1 SVHC properties under REACH Art. 57(a)-(c) and
#         correspond to CLP hazard categories H350, H340, H360.
#         All three CMR endpoints receive equal weight (3) consistent with
#         their equal legal standing as SVHC criteria.
#         Source: REACH Art. 57(a)-(c); CLP Reg. (EC) No 1272/2008.
#
#   3 — Persistent organic pollutant / Endocrine disruptor
#         POP is a proxy for PBT/vPvB properties (REACH Art. 57(d)-(e)).
#         Endocrine disruption corresponds to REACH Art. 57(f) and was
#         elevated to equivalent concern in the EU Chemicals Strategy for
#         Sustainability (European Commission, 2020).
#         Source: REACH Art. 57(d)-(f); EU CSS COM(2020) 667 final.
#
#   2 — Neurotoxin / Ecotoxin / Allergen (sensitisation Cat 1A)
#         OWN METHODOLOGICAL ADDITION: These properties are not among the
#         explicit SVHC criteria of Art. 57.  They are included because:
#         - Neurotoxicity is identified as a priority hazard class in the
#           EU CSS (European Commission, 2020, p. 9).
#         - Ecotoxicity is a recognised PBT-adjacent concern under REACH
#           Annex XIII and is central to environmental prioritisation.
#         - Sensitisation (allergen, CLP Cat 1A) is a harmonised CLH endpoint
#           with serious health consequences, treated here as intermediate.
#         Weight 2 was chosen to distinguish these from Tier-1 SVHC properties
#         while acknowledging their regulatory relevance.
#
#   1 — Sensitizer (Cat 1B) / Antimicrobial / Pesticidal activity
#         OWN METHODOLOGICAL ADDITION: Biological activity indicating
#         interaction with living systems (environmental or pharmacological)
#         but with lower systemic concern for humans than CMR/neurotoxic
#         properties.  Weight 1 signals biological relevance without implying
#         SVHC-level concern.
#
# AGGREGATION — additive summation
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# OWN METHODOLOGICAL ADDITION: ToxPi uses a weighted average of normalised
# domain scores (each domain rescaled to [0, 1]).  Here, the two domains are
# conceptually complementary rather than redundant: regulatory listing and
# intrinsic hazard measure different things and are largely independent
# (a substance may have many list memberships but lack ChEBI bio-activity data,
# or vice versa).  Additive summation preserves this independence and prevents
# normalisation from suppressing one domain when the other is zero.  The
# consequence is that the score is not bounded and must be interpreted in
# relative rather than absolute terms.
#
# Priority score = sum(list weights) + sum(bio-hazard weights)
#
# INTERPRETATION
# --------------
# **Fig 14a — Top-50 priority bar chart**
# The ranked bar chart answers: "which substances are most urgent?"  A high
# score reflects broad multi-list membership AND/OR strong hazard evidence.
# Substances near the top that are well-known SVHCs (BPA, acrylamide, phthalates)
# validate the scoring model; unexpected entries near the top warrant manual
# review to check whether the score is driven by data artefacts (e.g., a CAS
# number mapped to many InChIKeys).
#
# **Fig 14b — ECHA list presence heatmap (top 50)**
# Reveals which instruments drive each substance's priority score.  A row with
# many red cells = broad multi-list substance.  A row with one red cell = score
# driven by a single high-weight instrument; if that instrument is authorisation
# or restriction, the substance is a genuine concern; if it is registration,
# the weight contribution is minimal and the high rank is likely driven by
# bio-hazard evidence.
#
# **Fig 14c — UpSet plot (concern lists)**
# Shows how substances distribute across the concern-level lists only.
# Tall multi-list intersection bars = a chemical core that multiple binding
# instruments converge on — these are the highest regulatory priority.
# Source-specific bars identify substances that have fallen through gaps in
# cross-list harmonisation.
#
# **Fig 14d — Hazard profile bar chart**
# Answers: "what hazard types are most prevalent?"  A dominant CMR bar means
# that carcinogenic/mutagenic/reprotoxic properties drive most bio-hazard
# scores.  A large "no bio evidence" share confirms the ~79 % non-InChIKey
# problem: most substances cannot receive a bio-hazard score at all.
#
# **Fig 14e — Bubble chart (list score × bio score)**
# The four quadrants (SKILL.md §10) identify: Q1 = urgent (both dimensions
# high); Q2 = regulatory gap (high bio, low lists); Q3 = administrative breadth
# (high lists, no bio evidence); Q4 = low concern.  Q2 substances are the most
# actionable finding: hazard is confirmed but regulatory coverage is weak.
#
# **Fig 14f — Alluvial / Sankey diagram**
# Traces which hazard types flow to which regulatory instruments.  A wide band
# from "carcinogenic agent" to "candidate_list" confirms the CMR → SVHC
# pathway.  Hazard types without a wide band to any high-weight instrument
# indicate that the regulatory system has not fully captured that hazard class.
#
# **Fig 14g — Treemap (hazard classes)**
# Tile area = number of substances in the class; colour = mean priority score.
# Large tiles with low colour intensity = common but under-prioritised classes
# (regulatory gap candidates).  Small tiles with high colour intensity = rare
# but highly regulated classes.
#
# OUTPUTS
# -------
# output/figures/Analysis_14a_Top50_priority.pdf
# output/figures/Analysis_14b_List_heatmap.pdf
# output/figures/Analysis_14c_UpSet_concern_lists.pdf
# output/figures/Analysis_14d_Bio_hazard_profile.pdf
# output/figures/Analysis_14e_Bubble_priority.pdf
# output/figures/Analysis_14f_Sankey_activity_list.pdf
# output/figures/Analysis_14g_Treemap_priority.pdf
# output/tables/Analysis_14a_top50.csv
# output/tables/Analysis_14b_heatmap_matrix.csv
# output/tables/Analysis_14c_set_sizes.csv
# output/tables/Analysis_14c_intersections.csv
# output/tables/Analysis_14d_hazard_profile.csv
# output/tables/Analysis_14e_bubble_data.csv
# output/tables/Analysis_14f_flow_long.csv
# output/tables/Analysis_14f_flow_matrix.csv
# output/tables/Analysis_14g_treemap_stats.csv
# output/tables/prioritization.csv
# ==============================================================================

library(dplyr)
library(tidyr)
library(ggplot2)
library(readr)
library(here)
library(scales)
library(ggrepel)
library(UpSetR)
library(ggalluvial)
library(treemapify)
library(purrr)
library(forcats)
library(stringr)
library(writexl)

# ------------------------------------------------------------------------------
# Load and prepare data
# ------------------------------------------------------------------------------

chebi_raw <- read_csv(here("data", "processed", "chebi.csv"), show_col_types = FALSE)

# Valid ECHA list identifiers.  A small number of CSV-parsing artefacts
# (quoted chemical names mis-parsed as list types) are excluded by restricting
# to this controlled vocabulary.
valid_lists <- c(
  "reach_registrations", "harmonised_list", "dossier_evaluation",
  "eu_positive_list", "pesticides", "authorisation_list", "clh_process",
  "candidate_list", "svhc_identification", "substance_evaluation",
  "pbt_assessment", "ed_assessment", "restriction_list",
  "authorisation_process", "pops_list", "pops_process",
  "restriction_process", "sommatie_stoffen", "anhydrous"
)

# The raw CSV contains multiple rows per substance URI because the SPARQL
# query in chebi_to_table.rq groups by (substance, substance_name): the same
# URI can appear under several preferred labels (synonyms, ISO names, etc.).
# We collapse to one row per URI, concatenating unique non-missing values.
chebi <- chebi_raw |>
  group_by(substance) |>
  summarise(
    substance_name      = first(substance_name),
    inchikey            = first(inchikey),
    casNumbers          = paste(unique(na.omit(casNumbers)), collapse = "|"),
    ecNumbers           = paste(unique(na.omit(ecNumbers)),  collapse = "|"),
    bio_activity_labels = paste(unique(na.omit(bio_activity_labels)), collapse = "|"),
    echa_lists          = paste(unique(na.omit(echa_lists)),          collapse = "|"),
    .groups = "drop"
  )

# Explode pipe-separated list memberships to long format for aggregation
chebi_lists_long <- chebi |>
  separate_rows(echa_lists, sep = "\\|") |>
  filter(echa_lists %in% valid_lists)

# Explode pipe-separated biological activity labels to long format
chebi_bio_long <- chebi |>
  separate_rows(bio_activity_labels, sep = "\\|") |>
  filter(!is.na(bio_activity_labels), bio_activity_labels != "")

# ------------------------------------------------------------------------------
# Priority scoring
# ------------------------------------------------------------------------------

# Regulatory list weights (see SCORING METHODOLOGY in the file header)
# Source for hierarchy: REACH Reg. (EC) No 1907/2006, Arts. 57-73;
#   CLP Reg. (EC) No 1272/2008; EU POPs Reg. (EU) 2019/1021;
#   Reg. (EC) No 1107/2009.
# Numerical scale (0-5): own methodological choice (see header).
list_weights <- c(
  # SVHC identification and Candidate List: REACH Art. 57-59
  candidate_list        = 5,  svhc_identification   = 5,
  # Restriction (Art. 67-73) and Authorisation (Art. 60-66): binding obligations
  restriction_list      = 4,  restriction_process   = 3,
  authorisation_list    = 4,  authorisation_process = 3,
  # POPs: elimination-level obligation; EU POPs Reg. (EU) 2019/1021
  pops_list             = 4,  pops_process          = 3,
  # PBT/vPvB assessment: REACH Art. 57(d)-(e), Annex XIII
  pbt_assessment        = 3,
  # ED assessment: REACH Art. 57(f); elevated by EU CSS COM(2020) 667
  ed_assessment         = 3,
  # Harmonised CLP classification: CLP Reg. (EC) No 1272/2008, Annex VI
  harmonised_list       = 2,  clh_process           = 2,
  # Pesticide approval: Reg. (EC) No 1107/2009
  pesticides            = 2,
  # Ongoing evaluation without final hazard determination
  substance_evaluation  = 1,  dossier_evaluation    = 1,
  # Positive list: approved use under active oversight, not a hazard signal
  eu_positive_list      = 1,
  # Baseline administrative requirements: no hazard determination
  reach_registrations   = 0,  sommatie_stoffen      = 0,
  anhydrous             = 0
)

# Bio-hazard weights, split by impact domain for use in Fig 14d.
# Tier-1 weights (3): aligned with SVHC criteria, REACH Art. 57(a)-(f).
# Tier-2 weights (2): own methodological addition (see header for justification).
# Tier-3 weights (1): own methodological addition (biological activity signal).
bio_hazard_health <- c(
  # CMR Cat 1A/1B: REACH Art. 57(a)-(c); CLP H350/H340/H360
  # All three CMR endpoints receive weight 3 — equal legal standing as SVHC criteria.
  # Note: ChEBI uses "teratogenic agent" (RO:0000087 role) rather than the CLP term
  # "reproductive toxicant"; teratogenicity is the ontologically proximate role for
  # reproductive/developmental toxicity in the ChEBI role hierarchy.
  "carcinogenic agent"  = 3,
  "genotoxin"           = 3,
  "mutagen"             = 3,
  "teratogenic agent"   = 3,   # REACH Art. 57(c) CMR endpoint; ChEBI label for reprotox
  # Own addition: neurotoxicity (weight 2) — EU CSS COM(2020) 667 priority hazard
  "neurotoxin"          = 2,
  # Own addition: allergen / drug allergen (weight 2) — CLP sensitisation Cat 1A
  "allergen"            = 2,
  "drug allergen"       = 2,
  # Own addition: sensitizer (weight 1) — CLP sensitisation Cat 1B, lower tier
  "sensitizer"          = 1,
  # Own addition: antimicrobial (weight 1) — biological activity signal
  "antimicrobial agent" = 1
)
bio_hazard_env <- c(
  # Persistent organic pollutant: proxy for PBT/vPvB, REACH Art. 57(d)-(e)
  "persistent organic pollutant" = 3,
  # Endocrine disruptor: REACH Art. 57(f); EU CSS COM(2020) 667
  "endocrine disruptor"          = 3,
  # Own addition: ecotoxin (weight 2) — PBT-adjacent, REACH Annex XIII
  "ecotoxin"   = 2,
  # Own addition: pesticidal activity (weight 1) — biological activity signal;
  # regulatory approval under Reg. (EC) No 1107/2009 already captured in list score
  "herbicide"  = 1, "insecticide" = 1, "fungicide" = 1,
  "acaricide"  = 1, "nematocide"  = 1
)
bio_weights <- c(bio_hazard_health, bio_hazard_env)

# Helper: identify the highest-consequence ECHA list category for a substance,
# used to colour bar charts and bubble charts.
top_list_category <- function(lists_str) {
  v <- str_split(lists_str, "\\|")[[1]]
  if (any(v %in% c("candidate_list", "svhc_identification")))      return("SVHC / Candidate")
  if (any(v %in% c("restriction_list", "restriction_process")))    return("Restriction")
  if (any(v %in% c("authorisation_list", "authorisation_process"))) return("Authorisation")
  if (any(v %in% c("pops_list", "pops_process")))                  return("POP")
  if (any(v %in% c("pbt_assessment")))                             return("PBT")
  if (any(v %in% c("ed_assessment")))                              return("ED")
  if (any(v %in% c("harmonised_list", "clh_process")))            return("Harmonised / CLP")
  if (any(v %in% c("pesticides")))                                 return("Pesticides")
  return("Other")
}

list_score_df <- chebi_lists_long |>
  mutate(weight = list_weights[echa_lists]) |>
  group_by(substance) |>
  summarise(
    list_score = sum(weight, na.rm = TRUE),
    n_lists    = n_distinct(echa_lists),
    .groups    = "drop"
  )

bio_score_df <- chebi_bio_long |>
  mutate(weight = bio_weights[bio_activity_labels]) |>
  group_by(substance) |>
  summarise(bio_score = sum(weight, na.rm = TRUE), .groups = "drop")

priority <- chebi |>
  left_join(list_score_df, by = "substance") |>
  left_join(bio_score_df,  by = "substance") |>
  mutate(
    list_score     = replace_na(list_score, 0),
    bio_score      = replace_na(bio_score, 0),
    n_lists        = replace_na(n_lists, 0L),
    priority_score = list_score + bio_score,
    top_list_cat   = map_chr(echa_lists, top_list_category)
  ) |>
  arrange(desc(priority_score))

# Shared colour palette for list categories (used across multiple figures)
cat_colors <- c(
  "SVHC / Candidate" = "#c0392b",
  "Restriction"      = "#e67e22",
  "Authorisation"    = "#d35400",
  "POP"              = "#8e44ad",
  "PBT"              = "#2980b9",
  "ED"               = "#16a085",
  "Harmonised / CLP" = "#27ae60",
  "Pesticides"       = "#f39c12",
  "Other"            = "#95a5a6"
)

# ==============================================================================
# Fig 14a: Top 50 priority substances - horizontal bar chart
#
# INTENT
# ------
# Provides an at-a-glance ranked list of the fifty substances with the highest
# composite priority scores.  The colour of each bar indicates the most
# consequential ECHA list on which the substance appears, making it immediately
# clear whether high priority is driven by SVHC status, a restriction, a POP
# listing, or another instrument.  The chart is the primary output for
# communicating priority to a policy audience.
# ==============================================================================

top50 <- priority |> slice_head(n = 50)

p14a <- ggplot(top50,
               aes(x = priority_score,
                   y = reorder(substance_name, priority_score),
                   fill = top_list_cat)) +
  geom_col(width = 0.7) +
  geom_text(aes(label = priority_score), hjust = -0.15, size = 2.8) +
  scale_fill_manual(values = cat_colors, name = "Highest ECHA list") +
  scale_x_continuous(expand = expansion(mult = c(0, 0.15))) +
  labs(
    title    = "Top 50 priority substances",
    subtitle = "Priority score = sum of ECHA list weights (EU lists) + biological hazard score",
    x        = "Priority score",
    y        = NULL
  ) +
  theme_minimal(base_size = 10) +
  theme(
    plot.subtitle   = element_text(colour = "grey40"),
    legend.position = "bottom"
  )

print(p14a)
ggsave(p14a,
       filename = here("output", "figures", "Analysis_14a_Top50_priority.pdf"),
       device = "pdf", height = 14, width = 14, units = "in")

# Alphanumeric export 14a: ranked top-50 table
# Columns: rank, substance URI, preferred name, composite score, list sub-score,
#   bio-hazard sub-score, number of distinct ECHA lists, highest list category,
#   all ECHA lists (pipe-separated), all bio-activity labels (pipe-separated).
top50 |>
  mutate(rank = row_number()) |>
  select(rank, substance, substance_name, priority_score, list_score, bio_score,
         n_lists, top_list_cat, echa_lists, bio_activity_labels) |>
  write_csv(here("output", "tables", "Analysis_14a_top50.csv"))

# ==============================================================================
# Fig 14b: ECHA list presence heatmap - top 50 substances x 10 high-concern lists
#
# INTENT
# ------
# A binary presence/absence matrix that shows, for each of the 50 highest-
# priority substances, which of the ten most consequential ECHA regulatory
# instruments it appears on.  The heatmap reveals whether a substance's high
# score reflects broad multi-list coverage (a sign of deep regulatory concern)
# or is driven by a single high-weight instrument.  Substances with red cells
# spread across many columns warrant the most urgent attention.
# ==============================================================================

concern_lists <- c(
  "candidate_list", "svhc_identification", "restriction_list",
  "authorisation_list", "pops_list", "pbt_assessment",
  "ed_assessment", "harmonised_list", "pesticides", "clh_process"
)

list_labels <- c(
  candidate_list      = "Candidate list",
  svhc_identification = "SVHC ident.",
  restriction_list    = "Restriction list",
  authorisation_list  = "Authorisation list",
  pops_list           = "POPs list",
  pbt_assessment      = "PBT assessment",
  ed_assessment       = "ED assessment",
  harmonised_list     = "Harmonised list",
  pesticides          = "Pesticides",
  clh_process         = "CLH process"
)

heatmap_data <- top50 |>
  select(substance, substance_name, echa_lists, priority_score) |>
  separate_rows(echa_lists, sep = "\\|") |>
  filter(echa_lists %in% concern_lists) |>
  mutate(present = 1L) |>
  complete(
    nesting(substance, substance_name, priority_score),
    echa_lists = concern_lists,
    fill = list(present = 0L)
  ) |>
  mutate(
    substance_name = fct_reorder(substance_name, priority_score),
    echa_lists     = factor(echa_lists, levels = concern_lists,
                            labels = list_labels[concern_lists])
  )

p14b <- ggplot(heatmap_data,
               aes(x = echa_lists, y = substance_name, fill = factor(present))) +
  geom_tile(colour = "white", linewidth = 0.4) +
  scale_fill_manual(
    values = c("0" = "#f0f0f0", "1" = "#c0392b"),
    labels = c("0" = "Absent", "1" = "Present"),
    name   = NULL
  ) +
  labs(
    title    = "Presence on high-concern ECHA lists - top 50 substances",
    subtitle = "Ordered by priority score (highest priority at top)",
    x        = NULL, y = NULL
  ) +
  theme_minimal(base_size = 9) +
  theme(
    axis.text.x     = element_text(angle = 30, hjust = 1, size = 8),
    axis.text.y     = element_text(size = 7),
    plot.subtitle   = element_text(colour = "grey40"),
    legend.position = "top"
  )

print(p14b)
ggsave(p14b,
       filename = here("output", "figures", "Analysis_14b_List_heatmap.pdf"),
       device = "pdf", height = 14, width = 11, units = "in")

# Alphanumeric export 14b: binary presence/absence matrix (wide format)
# Rows: top-50 substances ordered by priority score (descending).
# Columns: substance_name, priority_score, then one column per concern list
#   (1 = present, 0 = absent), followed by n_lists_concern (count of concern
#   lists on which this substance appears).
heatmap_wide <- heatmap_data |>
  mutate(echa_lists = as.character(echa_lists)) |>
  select(substance_name, priority_score, echa_lists, present) |>
  pivot_wider(names_from = echa_lists, values_from = present, values_fill = 0L) |>
  arrange(desc(priority_score)) |>
  mutate(n_lists_concern = rowSums(across(where(is.integer))))
write_csv(heatmap_wide, here("output", "tables", "Analysis_14b_heatmap_matrix.csv"))

# ==============================================================================
# Fig 14c: UpSet plot - intersections of high-concern ECHA lists
#
# INTENT
# ------
# The UpSet plot extends the heatmap to the entire dataset (not just top 50)
# and focuses on the combinatorial structure of list co-membership.  Each bar
# in the intersection matrix shows how many distinct substances appear on
# exactly that combination of lists simultaneously.  This reveals which pairs
# or triplets of instruments overlap most (e.g. SVHC + Candidate + Restriction),
# informing decisions about where a single regulatory measure could achieve the
# broadest coverage.  Substances unique to a single list are equally visible
# and may indicate gaps in cross-instrument coordination.
# ==============================================================================

upset_concern <- chebi_lists_long |>
  filter(echa_lists %in% concern_lists) |>
  distinct(substance, echa_lists) |>
  mutate(present = 1L) |>
  pivot_wider(names_from = echa_lists, values_from = present, values_fill = 0L) |>
  select(-substance) |>
  as.data.frame()

names(upset_concern) <- list_labels[names(upset_concern)]

pdf(here("output", "figures", "Analysis_14c_UpSet_concern_lists.pdf"),
    width = 14, height = 8)
UpSetR::upset(
  upset_concern,
  nsets           = ncol(upset_concern),
  nintersects     = 25,
  order.by        = "freq",
  mb.ratio        = c(0.6, 0.4),
  text.scale      = c(1.2, 1.1, 1, 1, 1.1, 1),
  main.bar.color  = "#c0392b",
  sets.bar.color  = "#2c3e50",
  matrix.color    = "#c0392b",
  mainbar.y.label = "Number of substances in intersection",
  sets.x.label    = "Total per list"
)
dev.off()

# Alphanumeric export 14c — two complementary tables:
#
# (i) Set sizes: total number of substances per concern list.
upset_set_sizes <- upset_concern |>
  summarise(across(everything(), sum)) |>
  pivot_longer(everything(), names_to = "list", values_to = "n_substances") |>
  arrange(desc(n_substances))
write_csv(upset_set_sizes, here("output", "tables", "Analysis_14c_set_sizes.csv"))

# (ii) Intersection sizes: for every unique combination of lists that at least
#   one substance belongs to, the number of substances in that intersection.
#   The `combination` column contains the list names joined by " & "; an empty
#   string means the substance appears on none of the concern lists (excluded).
upset_intersections <- upset_concern |>
  mutate(combination = apply(
    across(everything()),
    MARGIN = 1,
    FUN    = function(x) paste(names(x)[x == 1L], collapse = " & ")
  )) |>
  filter(combination != "") |>
  count(combination, name = "n_substances") |>
  arrange(desc(n_substances))
write_csv(upset_intersections, here("output", "tables", "Analysis_14c_intersections.csv"))

# ==============================================================================
# Fig 14d: Biological hazard profile - most frequent hazardous activity labels
#
# INTENT
# ------
# The biological role annotations in chebi.csv are derived directly from the
# ChEBI ontology (property RO:0000087 "has role") and therefore represent a
# semantically authoritative, ontology-grounded signal of intrinsic hazard.
# This bar chart counts how many distinct substances carry each hazardous
# label, split by impact domain (human health vs. environment).  It answers
# the question: across the substances in this regulatory dataset, what are the
# most prevalent intrinsic hazard properties?  The chart also reveals the
# relative coverage of health-based vs. environment-based evidence, which is
# relevant for prioritisation workflows under, e.g., the EU Chemicals Strategy
# for Sustainability.
# ==============================================================================

bio_profile <- chebi_bio_long |>
  filter(bio_activity_labels %in% names(bio_weights)) |>
  count(bio_activity_labels, sort = TRUE) |>
  mutate(
    category = if_else(bio_activity_labels %in% names(bio_hazard_health),
                       "Human health", "Environmental"),
    bio_activity_labels = fct_reorder(bio_activity_labels, n)
  )

p14d <- ggplot(bio_profile,
               aes(x = n, y = bio_activity_labels, fill = category)) +
  geom_col(width = 0.7) +
  geom_text(aes(label = comma(n)), hjust = -0.15, size = 3.2) +
  scale_fill_manual(
    values = c("Human health" = "#c0392b", "Environmental" = "#27ae60"),
    name   = "Impact domain"
  ) +
  scale_x_continuous(expand = expansion(mult = c(0, 0.18)), labels = comma) +
  labs(
    title    = "Biological hazard profile",
    subtitle = "Most frequent hazardous activity labels derived from ChEBI ontology (human health vs. environment)",
    x        = "Number of substances",
    y        = NULL
  ) +
  theme_minimal(base_size = 12) +
  theme(
    plot.subtitle   = element_text(colour = "grey40"),
    legend.position = "bottom"
  )

print(p14d)
ggsave(p14d,
       filename = here("output", "figures", "Analysis_14d_Bio_hazard_profile.pdf"),
       device = "pdf", height = 7, width = 11, units = "in")

# Alphanumeric export 14d: hazard label frequency table
# Columns: bio_activity_label, impact domain (Human health / Environmental),
#   hazard_weight (from bio_weights), n_substances (distinct substances carrying
#   this label), pct_of_scored (share of substances with any bio-activity score).
n_with_bio <- nrow(bio_score_df |> filter(bio_score > 0))
bio_profile |>
  mutate(
    bio_activity_labels = as.character(bio_activity_labels),
    hazard_weight       = bio_weights[bio_activity_labels],
    pct_of_scored       = round(n / n_with_bio * 100, 2)
  ) |>
  arrange(desc(n)) |>
  select(bio_activity_label = bio_activity_labels, impact_domain = category,
         hazard_weight, n_substances = n, pct_of_scored) |>
  write_csv(here("output", "tables", "Analysis_14d_hazard_profile.csv"))

# ==============================================================================
# Fig 14e: Bubble chart - number of lists vs. biological hazard score
#
# INTENT
# ------
# The two scoring dimensions (regulatory breadth and intrinsic hazard) are
# largely independent: a substance can have many list memberships but no ChEBI
# bio-activity data (e.g. if it lacks an InChIKey), or it can have a high
# biological hazard score but appear on only a few lists.  This scatter plot
# plots every scored substance on these two axes simultaneously, with bubble
# size encoding the composite priority score.  Substances in the upper-right
# quadrant combine the widest regulatory coverage with the highest intrinsic
# hazard evidence and are unambiguously the most urgent.  Substances with high
# hazard but low list coverage may be under-regulated; substances with many
# list appearances but low hazard scores may reflect administrative overlap
# rather than genuine concern.
# ==============================================================================

plot_data_e <- priority |>
  filter(priority_score > 0)

top20_ids <- priority |>
  filter(priority_score > 0) |>
  slice_head(n = 7) |>
  pull(substance)

p14e <- ggplot(plot_data_e,
               aes(x = n_lists, y = bio_score,
                   size = priority_score, colour = top_list_cat)) +
  geom_point(alpha = 0.45) +
  geom_text_repel(
    data = plot_data_e |> filter(substance %in% top20_ids),
    aes(label = str_trunc(substance_name, 50)),
    size = 6, max.overlaps = 7, show.legend = FALSE, colour = "black",
    point.padding = 2.5, box.padding = 0.8,
    force = 3, force_pull = 0.4,
    segment.colour = "grey50", segment.size = 0.3
  ) +
  scale_colour_manual(values = cat_colors, name = "Highest\nECHA list") +
  scale_size_continuous(range = c(1, 12), name = "Priority\nscore") +
  scale_x_continuous(breaks = 0:20) +
  labs(
    title    = "Priority map - regulatory breadth vs. biological hazard",
    subtitle = "Bubble size = priority score  |  Labels = top 7 substances",
    x        = "Number of ECHA lists",
    y        = "Biological hazard score (health + environment)"
  ) +
  theme_minimal(base_size = 15) +
  theme(
    plot.subtitle        = element_text(colour = "grey40"),
    legend.position      = "right",
    legend.title         = element_text(size = 13),
    legend.text          = element_text(size = 15),
    legend.key.size      = unit(1.7, "lines")
  )

print(p14e)
ggsave(p14e,
       filename = here("output", "figures", "Analysis_14e_Bubble_priority.pdf"),
       device = "pdf", height = 9, width = 14, units = "in")

# Alphanumeric export 14e: full bubble chart data (all substances with score > 0)
# Each row is one substance. Quadrant assignment enables filtering in
# downstream interpretation:
#   Q1 (high_lists & has_bio)   = broad regulation + ChEBI hazard evidence (most urgent)
#   Q2 (low_lists  & has_bio)   = ChEBI hazard evidence but limited regulatory coverage (gap)
#   Q3 (high_lists & no_bio)    = wide regulatory presence but no ChEBI bio-activity data
#   Q4 (low_lists  & no_bio)    = low concern on both dimensions
# Thresholds: bio_score > 0 (has any ChEBI evidence); n_lists > median (broad coverage).
# Using bio_score > 0 rather than the median because the median is 0 for most
# substances (only ~21 % of substances have a ChEBI InChIKey match).
median_n_lists <- median(plot_data_e$n_lists)
plot_data_e |>
  mutate(
    has_bio  = bio_score > 0,
    quadrant = case_when(
      n_lists >  median_n_lists &  has_bio ~ "Q1: broad regulation & ChEBI hazard evidence",
      n_lists <= median_n_lists &  has_bio ~ "Q2: limited regulation & ChEBI hazard evidence",
      n_lists >  median_n_lists & !has_bio ~ "Q3: broad regulation & no ChEBI evidence",
      TRUE                                 ~ "Q4: limited regulation & no ChEBI evidence"
    )
  ) |>
  select(substance, substance_name, priority_score, list_score, bio_score,
         n_lists, top_list_cat, has_bio, quadrant) |>
  arrange(desc(priority_score)) |>
  write_csv(here("output", "tables", "Analysis_14e_bubble_data.csv"))

# ==============================================================================
# Fig 14f: Alluvial (Sankey) diagram - biological hazard group to ECHA list group
#
# INTENT
# ------
# The previous figures describe each dimension independently.  This alluvial
# diagram asks a structural question: given that a substance has a particular
# type of intrinsic hazard (e.g. carcinogenic/mutagenic), on which regulatory
# instruments does it tend to appear?  Conversely, which instruments capture
# a diverse range of hazard types, and which are dominated by a single hazard
# class?  The diagram reveals alignment (or misalignment) between the hazard
# basis of a substance and its regulatory coverage, which is a key input to
# gap analysis under the EU Chemicals Strategy for Sustainability.
# ==============================================================================

bio_group_map <- c(
  "carcinogenic agent"           = "Carcinogenic / Mutagenic",
  "genotoxin"                    = "Carcinogenic / Mutagenic",
  "mutagen"                      = "Carcinogenic / Mutagenic",
  "teratogenic agent"            = "Reproductive / Developmental toxicity",
  "neurotoxin"                   = "Neurotoxic",
  "allergen"                     = "Allergy / Sensitisation",
  "drug allergen"                = "Allergy / Sensitisation",
  "sensitizer"                   = "Allergy / Sensitisation",
  "persistent organic pollutant" = "POP / Environmental",
  "endocrine disruptor"          = "POP / Environmental",
  "ecotoxin"                     = "POP / Environmental",
  "herbicide"                    = "Pesticidal",
  "insecticide"                  = "Pesticidal",
  "fungicide"                    = "Pesticidal",
  "acaricide"                    = "Pesticidal",
  "nematocide"                   = "Pesticidal"
)

list_group_map <- c(
  candidate_list        = "SVHC / Candidate",
  svhc_identification   = "SVHC / Candidate",
  restriction_list      = "Restriction",
  restriction_process   = "Restriction",
  authorisation_list    = "Authorisation",
  authorisation_process = "Authorisation",
  pops_list             = "POPs",
  pops_process          = "POPs",
  pbt_assessment        = "PBT / ED",
  ed_assessment         = "PBT / ED",
  harmonised_list       = "Harmonisation / CLP",
  clh_process           = "Harmonisation / CLP",
  pesticides            = "Pesticides (list)"
)

alluvial_data <- chebi |>
  select(substance, bio_activity_labels, echa_lists) |>
  separate_rows(bio_activity_labels, sep = "\\|") |>
  separate_rows(echa_lists, sep = "\\|") |>
  filter(
    bio_activity_labels %in% names(bio_group_map),
    echa_lists %in% names(list_group_map)
  ) |>
  mutate(
    bio_group  = bio_group_map[bio_activity_labels],
    list_group = list_group_map[echa_lists]
  ) |>
  distinct(substance, bio_group, list_group) |>
  count(bio_group, list_group, name = "n") |>
  filter(n >= 3)

p14f <- ggplot(alluvial_data,
               aes(axis1 = bio_group, axis2 = list_group, y = n)) +
  geom_alluvium(aes(fill = bio_group), alpha = 0.65, width = 0.3) +
  geom_stratum(width = 0.3, fill = "grey92", colour = "grey60") +
  geom_label(stat = "stratum", aes(label = after_stat(stratum)), size = 3) +
  scale_x_discrete(
    limits = c("Biological hazard group", "ECHA list group"),
    expand = c(0.05, 0.05)
  ) +
  scale_fill_brewer(palette = "Set2", name = "Biological hazard group") +
  labs(
    title    = "From biological hazard to regulatory list",
    subtitle = "Which types of hazardous substance appear on which ECHA regulatory instruments?",
    y        = "Number of substances"
  ) +
  theme_minimal(base_size = 12) +
  theme(
    plot.subtitle   = element_text(colour = "grey40"),
    legend.position = "none"
  )

print(p14f)
ggsave(p14f,
       filename = here("output", "figures", "Analysis_14f_Sankey_activity_list.pdf"),
       device = "pdf", height = 9, width = 12, units = "in")

# Alphanumeric export 14f — two complementary tables:
#
# (i) Flow table (long format): number of substances linking each
#   bio-hazard group to each ECHA list group.  This is the direct source of
#   the Sankey diagram and can be used to identify dominant and sparse flows.
alluvial_data |>
  arrange(desc(n)) |>
  write_csv(here("output", "tables", "Analysis_14f_flow_long.csv"))

# (ii) Flow matrix (wide format): bio-hazard group as rows, ECHA list group
#   as columns, cell values = number of substances.  Easier to scan for gaps
#   (empty or near-zero cells where a hazard type is not captured by a list).
alluvial_data |>
  pivot_wider(names_from = list_group, values_from = n, values_fill = 0L) |>
  arrange(bio_group) |>
  write_csv(here("output", "tables", "Analysis_14f_flow_matrix.csv"))

# ==============================================================================
# Fig 14g: Treemap - biological activity group vs. mean priority score
#
# INTENT
# ------
# Aggregates the priority score to the level of broad hazard categories
# (derived from ChEBI biological roles) and presents the result as a treemap.
# Rectangle area encodes the number of substances in each hazard group,
# giving a sense of how large each group is relative to the others.  Colour
# encodes the mean priority score within the group, indicating whether a
# hazard class is on average receiving appropriate regulatory attention.
# A large rectangle with a pale colour (many substances, low mean priority)
# may indicate a systematically under-regulated hazard class.  A small but
# dark rectangle (few substances, high mean priority) suggests that a niche
# but highly consequential group of substances is being addressed.
# ==============================================================================

treemap_data <- chebi_bio_long |>
  mutate(bio_group = bio_group_map[bio_activity_labels]) |>
  filter(!is.na(bio_group)) |>
  left_join(priority |> select(substance, priority_score), by = "substance") |>
  group_by(bio_group) |>
  summarise(
    n_substances  = n_distinct(substance),
    mean_priority = mean(priority_score, na.rm = TRUE),
    .groups       = "drop"
  ) |>
  filter(n_substances >= 5)

p14g <- ggplot(treemap_data,
               aes(area = n_substances, fill = mean_priority, label = bio_group)) +
  geom_treemap() +
  geom_treemap_text(colour = "white", place = "centre", size = 14, grow = FALSE) +
  scale_fill_gradient(
    low  = "#f7f7b6",
    high = "#c0392b",
    name = "Mean priority\nscore"
  ) +
  labs(
    title    = "Treemap - biological hazard group vs. mean priority score",
    subtitle = "Area = number of substances in group  |  Colour = mean priority score"
  ) +
  theme_minimal(base_size = 12) +
  theme(plot.subtitle = element_text(colour = "grey40"))

print(p14g)
ggsave(p14g,
       filename = here("output", "figures", "Analysis_14g_Treemap_priority.pdf"),
       device = "pdf", height = 7, width = 10, units = "in")

# Alphanumeric export 14g: aggregated hazard-group statistics
# Extends treemap_data with distributional statistics (median, SD, min, max)
# to support interpretation beyond the mean shown in the figure.
chebi_bio_long |>
  mutate(bio_group = bio_group_map[bio_activity_labels]) |>
  filter(!is.na(bio_group)) |>
  left_join(priority |> select(substance, priority_score), by = "substance") |>
  group_by(bio_group) |>
  summarise(
    n_substances   = n_distinct(substance),
    mean_priority  = round(mean(priority_score,   na.rm = TRUE), 2),
    median_priority = round(median(priority_score, na.rm = TRUE), 2),
    sd_priority    = round(sd(priority_score,     na.rm = TRUE), 2),
    min_priority   = min(priority_score,           na.rm = TRUE),
    max_priority   = max(priority_score,           na.rm = TRUE),
    .groups = "drop"
  ) |>
  filter(n_substances >= 5) |>
  arrange(desc(mean_priority)) |>
  write_csv(here("output", "tables", "Analysis_14g_treemap_stats.csv"))

# ==============================================================================
# Export full priority table (all substances)
# ==============================================================================

dir.create(here("output", "tables"), showWarnings = FALSE, recursive = TRUE)

prioritization <- priority |>
  select(
    substance, substance_name, inchikey, casNumbers, ecNumbers,
    priority_score, list_score, bio_score,
    n_lists, top_list_cat, echa_lists, bio_activity_labels
  ) 

write_csv(prioritization, here("output", "tables", "prioritization.csv"))
write_xlsx(prioritization, here("output", "tables", "prioritization.xlsx"))


message(sprintf(
  "Analysis 14 complete: %d unique substances scored | Top substance: '%s' (score: %g) | CSV saved",
  nrow(priority),
  priority$substance_name[1],
  priority$priority_score[1]
))
